### ISSUE TITLE
How to use multiple screens

### ISSUE THREAD

**Issue by Geekume** [viduraembedded/Raspberry-Pi-Pico#1]
With your 1.8 inch screen library how do you add a second tft screen?

**Comment by viduraembedded** [comment]
Hello

If i understood correctly, you want to use 2tft displays to RP Pi Pico .

If above the case then you can use the different spi on the Pi Pico and
drive the TFT LCD.

You can also share the same spi bus for another TFT and declare different
gpio for CS, RST and RS/DC pins.

Please let me know if you any questions.

Thanks,
Vidura Embedded

**Comment by Geekume** [comment]
hey sorry I digged through a bit and actually had to change st7735.c because it wasn't configured to have multiple cs pins 
but yeah got it to work by copying and pasted voids from st7735.c and making the cs and rst cs2 and rst 2 and having eveything else wired together
